# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 004bcaedbadf4ba9f2e5b97b976ebf26ac15b619194a7549d555d004c011d3e834228862d628f5da8951648d3a88e3bd07be5210698bcbdbb4da39e5b7ad375b

test:
  secret_key_base: 34452ecc875455e4e6dd81fb0720e2ee540eff31273fb0993fc9782812e60e5a34f450fe3c36727cc106e9faec4456f4aa5a0cb0b3a1abb96344e3b23e0ed812

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
